use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq)]
pub enum Framework {
    Anchor,
    Native,
    Unknown,
}

#[derive(Debug, Clone)]
pub struct ProjectInfo {
    pub framework: Framework,
    /// Path to the compiled .so file
    pub so_path: PathBuf,
    /// Path to the IDL JSON — None for native programs
    pub idl_path: Option<PathBuf>,
    /// Program name derived from the .so filename
    pub program_name: String,
}

/// Auto-detect the project type from the current directory.
/// Call this from the CLI — it reads cwd automatically.
pub fn detect(project_root: &Path) -> Result<ProjectInfo> {
    // 1. Is it an Anchor project? (has Anchor.toml)
    let is_anchor = project_root.join("Anchor.toml").exists();

    // 2. Find the compiled .so in target/deploy/
    let deploy_dir = project_root.join("target/deploy");
    let so_path = find_so_file(&deploy_dir)
        .context("Could not find a compiled .so in target/deploy/. Run `anchor build` first.")?;

    let program_name = so_path
        .file_stem()
        .unwrap_or_default()
        .to_string_lossy()
        .to_string();

    // 3. Find the IDL JSON (only for Anchor)
    let idl_path = if is_anchor {
        let idl_dir = project_root.join("target/idl");
        find_idl_file(&idl_dir, &program_name)
    } else {
        None
    };

    Ok(ProjectInfo {
        framework: if is_anchor {
            Framework::Anchor
        } else {
            Framework::Native
        },
        so_path,
        idl_path,
        program_name,
    })
}

/// Find the first .so file in the deploy directory.
/// Skips the standard keypair .so files (ending in -keypair.json).
fn find_so_file(deploy_dir: &Path) -> Option<PathBuf> {
    let pattern = deploy_dir.join("*.so").to_string_lossy().to_string();
    glob::glob(&pattern).ok()?.filter_map(|e| e.ok()).find(|p| {
        // skip keypair .so files generated by anchor
        !p.to_string_lossy().contains("keypair")
    })
}

/// Find the IDL JSON matching the program name.
fn find_idl_file(idl_dir: &Path, program_name: &str) -> Option<PathBuf> {
    let exact = idl_dir.join(format!("{}.json", program_name));
    if exact.exists() {
        return Some(exact);
    }

    // fallback: first .json in target/idl/
    let pattern = idl_dir.join("*.json").to_string_lossy().to_string();
    glob::glob(&pattern).ok()?.filter_map(|e| e.ok()).next()
}
