[package]
name = "pyron-parser"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# inherit versions from workspace root
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = "1" # nicer test failure output
